name: Trigger auto deployment for ai-container-maras-test-image

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ai-container-maras-test-image-AutoDeployTrigger-6ed571f3-7f8a-4ed3-9378-97083167554e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AICONTAINERMARASTESTIMAGE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AICONTAINERMARASTESTIMAGE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AICONTAINERMARASTESTIMAGE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.AICONTAINERMARASTESTIMAGE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AICONTAINERMARASTESTIMAGE_REGISTRY_PASSWORD }}
          containerAppName: ai-container-maras-test-image
          resourceGroup: rg-ai-maras-test-image
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


